### ISSUE TITLE
v4 release

### ISSUE THREAD

**Issue by XVilka** [aquynh/capstone#1096]
Long awaited, compared to the v3 one. Would be nice if distributions will finally package capstone with a lot of fixes from the `next` branch.

[![Packaging status](https://repology.org/badge/vertical-allrepos/capstone.svg)](https://repology.org/metapackage/capstone/versions)

**Comment by radare** [comment]
ping

**Comment by aquynh** [comment]
I will put up a list of TODO for this release.

**Comment by XVilka** [comment]
Is there any roadmap or something like that? Or maybe issues blocking it?

**Comment by aquynh** [comment]
No, after fixing some outstanding bugs reported by Google Autofuzz, we can
release it.

**Comment by aquynh** [comment]
the first step is to merge "next" to "master". i did this in the branch https://github.com/aquynh/capstone/tree/merge. 

can you guys test this branch, and report if radare has any issues, before i do actual marge into master?

**Comment by aquynh** [comment]
i renamed the "merge" branch to v4, at https://github.com/aquynh/capstone/tree/v4

**Comment by ret2libc** [comment]
@aquynh any news on this? Are you waiting for a particular date? Are you waiting for a particular feature or bugfix? What is missing from releasing 4.0?

Other months have passed since last comments on this topic. Most distributions still ship 3.0.5 because it's the last "stable", which is so much older than master.

**Comment by aquynh** [comment]
we released v4.0, thanks.
