### ISSUE TITLE
Question about the way to change parts of disassembled codes into data

### ISSUE THREAD

**Issue by pk3492** [aquynh/capstone#1535]
Hi, all.

When I disassemble some codes (- not with capstone since I have never used capstone), some data is disassembled as codes and some code is disassembled as data (e.g., in some (rare) cases, data is placed in .text section as read-only data). 
I think that can happen in any disassembler. 

In that context, suppose I found such areas manually after I got the disassembly results and I want to fix it.
In that case, is it possible to designate some addresses (or a range of addresses) as "data"?

If I cannot designate such address as data before disassembling, it can potentially cause a disassembler to generate wrong control flows again, which makes disassembly results wrong.

**Comment by tmfink** [comment]
@pk3492 Capstone is a lower-level disassembler. Capstone will only try to disassemble a buffer bytes linearly with the assumption that everything is code. You are trying to implement a recursive disassembler (like IDA or other tools), but Capstone only does linear disassembly. You can think of Capstone as a low-level building block that can be used to create a recursive disassembler.

To implement what you want, you could pass in the buffer of bytes you want to disassemble, but set the `count` argument to `1`. After disassembling each instruction, you can decide whether the following bytes are data or code. If you think the following bytes are in-inline data, then skip over them; otherwise, disassemble them. 

Capstone does support a [skipdata mode](https://www.capstone-engine.org/skipdata.html) (Capstone supports this in version 4 and later, you can ignore the comment about the `next` branch).
To quote:

> By default, Capstone stops disassembling when it encounters a broken instruction. Most of the time, the reason is that this is data mixed inside the input, and it is understandable that Capstone does not understand this “weird” code.
> 
> Typically, you are recommended to dertermine yourself where the next code is, and then continue disassembling from that place. However, in some cases you just want to let Capstone automatically skip some data until it finds a legitimate instruction, then just carries on from there. Hence, the SKIPDATA mode is introduced for this purpose.
> 
> In general, this solution is suboptimal because Capstone can make a mistake deciding what is data, what is code. Only rely on a fact that input can be disassembled to determine the code start from there is fundamentally wrong, so you are warned: only use this mode when you know what you are doing.

Relevant links:
- [C language code example](https://www.capstone-engine.org/lang_c.html)
- `capstone.h`: https://github.com/aquynh/capstone/blob/15929435923c34d17b1412307a91615f13142e34/include/capstone/capstone.h#L486-L524
- [Skipdata mode tutorial](https://www.capstone-engine.org/skipdata.html)

**Comment by pk3492** [comment]
Thank you for your comment. 
And, I didn't know how it works. But, your description really helps me understand Capstone.
