### ISSUE TITLE
[Important]  Version release consultation and request

### ISSUE THREAD

**Issue by gaojh86** [aquynh/capstone#1980]
Thank you for your excellent open source software. 
Some of our company's products use the disassembly function provided by capstone. 
We'd like to ask，when is the latest rc version expected to be released? 
Please, can you release it as soon as possible?

Thank you very much.

**Comment by XVilka** [comment]
It will likely happen after LLVM auto-sync work is done: https://github.com/capstone-engine/capstone/pull/1949

**Comment by gaojh86** [comment]
> 



> It will likely happen after LLVM auto-sync work is done: #1949

Thank you for replying. Do you know when that might be completed?

**Comment by Rot127** [comment]
> Thank you for replying. Do you know when that might be completed?

Hard to say but here is the plan and "good to know" things:

https://github.com/capstone-engine/capstone/pull/1949 should be completed somewhere in May (currently I am fixing bugs for setting the detail information, afterwards clean up and extensive documentation awaits).
Once it is done we have a better idea how long it takes to update other archs.

On the other hand #1949 will get proper documentation about the update process, so that simpler architectures can be updated by other people who have not looked into it half a year.

How exactly the release schedule would look like for this is probably @kabeor's take to say.

**Comment by Rot127** [comment]
Also see https://github.com/capstone-engine/capstone/pull/1949#issuecomment-1508287610 and its answer (https://github.com/capstone-engine/capstone/pull/1949#issuecomment-1508298181).

**Comment by XVilka** [comment]
@gaojh86 could be closed now, I suppose?

**Comment by gaojh86** [comment]
Thanks for the release。
