### ISSUE TITLE
LNK2019 unresolved external symbol "id2name", the msvc project config need update

### ISSUE THREAD

**Issue by No-47** [aquynh/capstone#2177]
I try to compile the capstone v5.0.1 project on windows using .\msvc\capstone.sln.  bug all test units failed.
so many LNK2019 errors, just like: unresolved external symbol "id2name"
I found and fixed the bug.
The cause of the problem is that the static library project (capstone_static) forgot to include the file: Mapping.c. it just included Mapping.h. that's why so many symbols do not defined.
![image](https://github.com/capstone-engine/capstone/assets/18509370/613242ab-4320-430c-8c38-7c18156c8a8b)
so that's the reason why all the test units project report LNK2019. 
when you add it, everything is ok.
but still one error, I haven't had time to see why：
![image](https://github.com/capstone-engine/capstone/assets/18509370/e8942fa0-41f1-4333-88fd-1074a0178d98)
This seems to be a problem with the project configuration not being updated. This is a piece of cake to repair, so I won’t go into details.

**Comment by No-47** [comment]
the org errors just like:
![image](https://github.com/capstone-engine/capstone/assets/18509370/ad9bcd21-ac63-4e35-ace6-09d7cebcfc87)
![image](https://github.com/capstone-engine/capstone/assets/18509370/a224176c-88a7-439e-8d57-48907f24ecee)

**Comment by g0th1c54e4** [comment]
兄弟你解决好了吗，我也是这个问题

**Comment by Rot127** [comment]
@g0th1c54e4 Please add comments in English only.
@No-47 Sorry, it just got to my attention again. Would you mind opening a PR for this? I won't have a Windows machine/VM in a reasonable time ready.

**Comment by g0th1c54e4** [comment]
@Rot127

I encountered the same issue as the original poster while using **Capstone 5.0.1**. The compilation process in Visual Studio went smoothly without any exceptions reported by the compiler. However, the issue arises with the Capstone static library after the compilation. When I link the Capstone static library in my project, the compiler reports two errors: **"LNK2001"** and **"LNK1120"**. The "LNK2001" error specifically points out that the symbol **"id2name"** in the Capstone static library cannot be properly resolved.
![error](https://github.com/user-attachments/assets/082984c9-af05-48b9-af41-08369c94ca6f)


To address this, I went back to the Capstone source code and located the problematic point as indicated by the compiler. This point is in the **file _X86Mapping.c_**, **line _943_**.
![项目3](https://github.com/user-attachments/assets/a5ca66a2-3ec5-436f-af66-521a0cc6f5ba)
```
const char *X86_group_name(csh handle, unsigned int id)
{
#ifndef CAPSTONE_DIET
	return id2name(group_name_maps, ARR_SIZE(group_name_maps), id);
#else
	return NULL;
#endif
}
```


Since I am not familiar with the entire Capstone source code, I could only take the following approach to mitigate the issue:
I located the code for **id2name** **_(lines 55-67 in Mapping.c)_**, copied this code, and then went back to the problematic point. I pasted the copied code above the problematic point and renamed it to "**id2name_fix**". Finally, I replaced the "**id2name**" at the problematic point with "**id2name_fix**".
![项目2](https://github.com/user-attachments/assets/2b83f929-9fae-445d-b3f0-f18e62ee1d52)
```
const char *id2name_fix(const name_map *map, int max, const unsigned int id);
const char *id2name_fix(const name_map *map, int max, const unsigned int id)
{
	int i;

	for (i = 0; i < max; i++) {
		if (map[i].id == id) {
			return map[i].name;
		}
	}

	// nothing match
	return NULL;
}

const char *X86_group_name(csh handle, unsigned int id)
{
#ifndef CAPSTONE_DIET
	return id2name_fix(group_name_maps, ARR_SIZE(group_name_maps), id);
#else
	return NULL;
#endif
}
```

This workaround successfully mitigated the issue. Although this solution may not be elegant, it at least stops the compiler from reporting errors.

---------------other info
Capstone Version: 5.0.1 (source from release)
Compiler: msvc (Visual Studio 2022 Ver.17.9.0 64Bit )
System: Windows 11 23H2

**Comment by Rot127** [comment]
Could you test the build on the current `next` branch. I remember someone added Mapping.c to the CMakeFiles I think.

**Comment by Rot127** [comment]
The `msvc` files are removed on the `next` branch and since the normal `cmake` build is working fine on Windows I close this here.

Just tested the build on the current `v5` branch as well:
```
cmake.exe -B build
cmake.exe --build build
./build/Debug/cstool.exe
....
```
