### ISSUE TITLE
ARM64: Unable to decode `luti2` and `luti4` instructions

### ISSUE THREAD

**Issue by TIHan** [aquynh/capstone#2269]
When using `cstool`, I'm not able to decode ARM64 `luti2` and `luti4` instructions.

Here are some examples:

Hexcode: `00B02045`
Should output: `luti2   z0.b, { z0.b }, z0[0]`
But `cstool` fails and stops decoding altogether.

Hexcode: `55B17545`
Should output: `luti2   z21.b, { z10.b }, z21[1]`
But again, `cstool` fails and stops decoding.

**Comment by Rot127** [comment]
So after investigating it a little, I couldn't spot the problem immediately. Which means it is likely somewhere in the generated files. Because we will update to LLVM 18 soon anyway, it is better to fix it there IMHO (if it doesn't solve itself anyways). Same for https://github.com/capstone-engine/capstone/issues/2268

**Comment by TIHan** [comment]
That makes sense. Thank you for looking at it. Will be looking forward to the LLVM 18 update.

**Comment by Rot127** [comment]
It was indeed added in LLVM-18. So this will be closed once  https://github.com/capstone-engine/capstone/pull/2298 is merged.
