### ISSUE TITLE
Null Byte Truncation in Cython bindings

### ISSUE THREAD

**Issue by secretsquirrel** [aquynh/capstone#243]
I ran into this issue when another project used cython bindings vs straight python bindings:
```
md = Cs(CS_ARCH_X86, CS_MODE_32)
        for k in md.disasm(self.f.read(12), 0):
           print k.bytes
```

Python bindings (correct):
bytearray(b'\xe8\xfc\xad\x00\x00')
Cython bindings (not correct):
bytearray(b'\xe8\xfc\xad')

Not sure if there's something you can with it.  I built in a workout within my code to append the null bytes as I used the values in k.bytes straight away.

**Comment by aquynh** [comment]
can you post the full source code for testing?

thanks.

**Comment by aquynh** [comment]
so is the `k.size` correct?

and which version are you using? can you post the output of `capstone.debug()` ?

**Comment by secretsquirrel** [comment]
Master (https://github.com/aquynh/capstone/commit/b53a59af53ffbd5dbe8dbcefba41a00cf4fc7469)
```

from capstone import *
from binascii import hexlify

md = Cs(CS_ARCH_X86, CS_MODE_32)

for k in md.disasm("\xe8\xfc\xad\x00\x00", 0):
    print hexlify(k.bytes)
```
Output:
cython:'e8fcad'
python: e8fcad0000

```
capstone.debug()
```
output:
'Cython-standard-arm-arm64-mips-ppc-sparc-sysz-xcore-x86-c3.0-b3.0'

**Comment by secretsquirrel** [comment]
yes k.size is correct... 

I implemented a work around here for my project (https://github.com/secretsquirrel/the-backdoor-factory/blob/master/intel/intelCore.py#L86) that uses size and appends the null bytes on the end.

**Comment by aquynh** [comment]
finally got sometime to work on this. can you confirm the latest code fixes your issue?

- if you still want **3.0.1** version, pull & compile Cython binding from `v3` branch. no need to reinstall your 3.0 core (even this is recommended, as `v3` fixes some X86 issues)

- if you want to try **4.0** version, try to pull & compile both **core** & Cython binding from the `next` branch. (core needs to be reinstalled with this due to the bumped version)

thanks

**Comment by secretsquirrel** [comment]
This does fix the issue. 

Thanks.
