### ISSUE TITLE
Remove MSVC specific build files.

### ISSUE THREAD

**Issue by Rot127** [aquynh/capstone#2457]
### Feature

- [ ] New architecture module
- [ ] Support for processor extension
- [ ] Add more instruction details (elaborated below)
- [ ] Binding support for: `language`
- [x] Other (elaborated below)

**Describe the feature you'd like**
We can remove all MSVC specific build files. CMake can handle Windows builds just fine. And they contain a lot of duplicate and outdated stuff.

**Additional context**

Would address issues like this: https://github.com/capstone-engine/capstone/issues/2317

**Comment by richard-broadhurst** [comment]
The basic msvc .sln projects don't build because of inline and the VS2010 project files with their C behaviour.
I far prefer just getting the prebuilt .sln and .vcxproj files, but these are out of date and don;t match the language used.
I prefer to fix them than have to install or use cmake though (and will locally)!

**Comment by Rot127** [comment]
If I understand you correctly you would like to have the .vcxproj files back?

I don't think that the very little comfort Windows users gain with the `.sln` project justifies the extra maintenance.
Installing cmake is very straight forward on Windows in Visual Studio ([it apparently just needs one tick of a box](https://learn.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170)) and not too much of a hustle.
