### ISSUE TITLE
Compiling Trtion with capstone

### ISSUE THREAD

**Issue by xxA1eksandrxx** [aquynh/capstone#2490]
For compiling to compile triton, you need to capstone-engine. I install "sudo apt-get install libcapstone-dev", and I got an error:
/home/test/Triton/src/libtriton/includes/triton/externalLibs.hpp:35:16: fatal error: capstone/riscv.h: There is no such file or directory
   35 |       #include <capstone/riscv.h>

**Comment by Rot127** [comment]
Ouh, so you are on Ubuntu?
Because there Capstone is on version `v4`, which is no longer supported.

It is better if you build and install capstone yourself:

```
git clone https://github.com/capstone-engine/capstone.git
cd capstone
git checkout v5
cmake -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build
sudo cmake --install build
```

But it is better to check how Triton wants to have Capstone installed. Which version etc.
Also, which Trinton are you talking about? I find multiple projects of this name.

**Comment by xxA1eksandrxx** [comment]
https://github.com/JonathanSalwan/Triton

**Comment by Rot127** [comment]
Ok, then you need to build it yourself as described above. They require v5. Should be very straight forward.

**Comment by xxA1eksandrxx** [comment]
thanks for the help
