### ISSUE TITLE
Backward compatibility for ARM64.

### ISSUE THREAD

**Issue by aquynh** [aquynh/capstone#2536]
### Feature

- [ ] New architecture module
- [ ] Support for processor extension
- [ ] Add more instruction details (elaborated below)
- [ ] Binding support for: `language`
- [x] Other (elaborated below)

Please have API backward compatibility, so consts like CS_ARCH_ARM64, CS_ARM64_xxx still work out of the box - without having to do any configuration

**Comment by Rot127** [comment]
For Python they are still missing (related to https://github.com/capstone-engine/capstone/issues/2468).

But for C we have the compatibility header. Which can be enabled with a single "#define" (as documented [here](https://github.com/capstone-engine/capstone/blob/next/docs/cs_v6_release_guide.md#notes-about-aarch64-systemz-and-arm-renaming)).

Switching to `v6-Alpha` or any other version requires code changes anyways. Because instruction enumerations and details got more precise. Just as in the releases from `v3`, `v4` and `v5`. With `v6` this should no longer happen from now on.
So if people have to touch their code a last time between releases anyways, in my opinion a single `#define` is not too much.
