### ISSUE TITLE
enum cs_mode seems quirky

### ISSUE THREAD

**Issue by n1tehawk** [aquynh/capstone#277]
"CS_MODE_ARM = 0" is identical to the default ("no-op") CS_MODE_LITTLE_ENDIAN. The next enum constant is "CS_MODE_16 = 1 << 1" = 2, so the "1" is absent from this enum.

I'm wondering if this shouldn't be "CS_MODE_ARM = 1 << 0" (= 1)...

**Comment by aquynh** [comment]
On Sat, Mar 7, 2015 at 7:32 PM, NiteHawk <notifications@github.com> wrote:

> "CS_MODE_ARM = 0" is identical to the default ("no-op")
> CS_MODE_LITTLE_ENDIAN. The next enum constant is "CS_MODE_16 = 1 << 1" = 2,
> so the "1" is absent from this enum.
>
> I'm wondering if this shouldn't be "CS_MODE_ARM = 1 << 0" (= 1)...
>

with the current choice, because CS_MODE_LITTLE_ENDIAN=0, it becomes the
default mode as for ex: CS_MODE_ARM == CS_MODE_ARM + CS_MODE_LITTLE_ENDIAN.
so this means Little Endian is the default mode if you dont pass anything.

on the value of CS_MODE_ARM = 0, i dont see anything wrong with that, as
any value should be OK, so we save a value for future by starting at 0.

thanks.

**Comment by n1tehawk** [comment]
I still find it a little odd, as such a `CS_MODE_ARM` is indistinguishable from `CS_MODE_LITTLE_ENDIAN`, unlike any other CS_MODE_* (let's say `CS_MODE_64 + CS_MODE_LITTLE_ENDIAN`). That could possibly also be a concern when bindings might rely on consecutive numbering. (E.g. I have no idea what the actual value of `CS_MODE_ARM` would be in _bindings/ocaml/capstone.ml_ ?)

But anyway, I'll take your word on "it's meant to be that way". Thus I'm closing this issue.

Thanks for your time!

**Comment by aquynh** [comment]
actually i agree with you that `CS_MODE_ARM =  CS_MODE_LITTLE_ENDIAN` is a bit confused, and it is indeed better to choose a different value for `CS_MODE_ARM`. but this is not really an issue in practice, so i dont see many good reasons to change it now.

on Ocaml, the hardware modes are handled as variant types (as you can find in `capstone.ml`), so you never actually use (or see) them as values. Then this is not an issue, either.

Thanks.
