### ISSUE TITLE
vaguely documented instruction id

### ISSUE THREAD

**Issue by mrexodia** [aquynh/capstone#333]
Hey,

Recently I did some analysis stuff with capstone and at first I couldn't find where the `x86_insn` [enum](https://github.com/aquynh/capstone/blob/next/include/capstone/x86.h#L329) was used. Then I did some more digging and it turned out that the field that uses this value is `cs_insn.id` ([here](https://github.com/aquynh/capstone/blob/next/include/capstone/capstone.h#L257)). Maybe it is a good idea to rename `x86_insn` to `x86_insn_id` instead (and obviously for all the other architectures too)?

If you think this is a good idea I will do a pull request.

**Comment by aquynh** [comment]
the problem is that this changes the interface, thus all apps are currently using this enum must be modified. a move like this must be avoided at all cost, if possible.

while `x86_insn` is not a bad name IMO, i agree that the docs must be improved. we already have some docs in `capstone.h`, like this:

```
        // Instruction ID
        // Find the instruction id from header file of corresponding architecture,
        // such as arm.h for ARM, x86.h for X86, etc...
        // This information is available even when CS_OPT_DETAIL = CS_OPT_OFF
        // NOTE: in Skipdata mode, "data" instruction has 0 for this id field.
        unsigned int id;
```

we  can put more information here to point to `x86_insn` in `x86.h.`, `arm_insn` in `arm.h`, etc.

at the same time, we can also document `x86_insn` in `x86.h` about how to use that.

if you do a PR like this, i will happily merge it. thanks.
