### ISSUE TITLE
Uninitialized memory reads in X86 Disassembler

### ISSUE THREAD

**Issue by radare** [aquynh/capstone#497]
I have found that several instructions produce invalid memory reads in the prefix. This bug can be reproduced with an ASAN build or just with valgrind disassembling the  `rasm2 -a x86 -b64 -d ff0000` bytes. Here's a C test case:

```
#include <stdio.h>
#include <stdlib.h>
#include <capstone/capstone.h>


int main()
{
        int count;
        static csh handle;
        cs_insn *insn;
        uint8_t fun[] = "\xff\x00\x00";
        cs_err err = cs_open(CS_ARCH_X86, CS_MODE_32, &handle);
        if (err) {
                printf("Failed on cs_open() with error returned: %u\n", err);
                abort();
        }

        count = cs_disasm(handle, fun, 3, 0, 1, &insn);
        printf ("%d\n", count);
        return 0;
}
```

The offending lines are in:

* X86DisassemblerDecoder:370
* X86DisassemblerDecoder:1220
* X86Disassembler:124
* X86Disassembler:100

**Comment by radare** [comment]
Looks like the prefixPresent variable is not properly initialized, because its a lot of memory and instead of setting the entire array to zeroes, only some of them are set, but then it results in some instructions causing memreads on those elements of the array producing disassembling problems.

Also, the prefixLocations is an array of uint64 , which looks overbloated to me, maybe we can just use relative addressing for the locations and then use a single bit for the prefixPresent boolean value, this will reduce capstone memory requirements. And the cpu penalty shouldnt be too hard.

A quickfix consists in initializing the entire boolean array with zeroes.

**Comment by aquynh** [comment]
this may come from this commit: https://github.com/aquynh/capstone/pull/484 (related issue https://github.com/aquynh/capstone/issues/483)

please send a PR if you can confirm & fix this bug.

**Comment by aquynh** [comment]
@onesbug: do you have any comments?

**Comment by onesbug** [comment]
L've just come back from leave.
My intention is to improve performance because memset is really taking time.
I think my code has no problem.(but then I found I losted prefix 0x64 in X64 mode),
But I must confess my code is non-standard for valgrind.
i tried to reproduce you testcase,this is my code:
```c++
int main()
{
	    int count;
        static csh handle;
        cs_insn *insn;
        uint8_t fun[] = "\xff\x00\x00";
        cs_err err = cs_open(CS_ARCH_X86, CS_MODE_32, &handle);
        if (err) {
                printf("Failed on cs_open() with error returned: %u\n", err);
                abort();
        }

        count = cs_disasm(handle, fun, 3, 0, 1, &insn);
	cs_free(insn, count);
        cs_close(&handle);
        printf ("%d\n", count);
        return 0;
}
```
i used valgrind to catch information:

bug@ubuntu:~/capstone/suite/benchmark$ valgrind --tool=memcheck ./test_iter_benchmark
==14687== Memcheck, a memory error detector
==14687== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==14687== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==14687== Command: ./test_iter_benchmark
==14687== 
1
==14687== 
==14687== HEAP SUMMARY:
==14687==     in use at exit: 0 bytes in 0 blocks
==14687==   total heap usage: 4 allocs, 4 frees, 13,038 bytes allocated
==14687== 
==14687== All heap blocks were freed -- no leaks are possible
==14687== 
==14687== For counts of detected and suppressed errors, rerun with: -v
==14687== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
bug@ubuntu:~/capstone/suite/benchmark$ 

Could you tell me how to reproduce it?thanks.

**Comment by radare** [comment]
Doesnt seems to crash on latest git. i have updated the tip commit in r2, removed my temporal patch and tested with asan.
